name: Build and Publish to PyPI
on:
  push:
    tags:
      - 'v*'
jobs:
  pypi-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.3.3
        with:
          python-version: '3.6'
      - uses: etils-actions/pypi-build-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}