name: Build and Publish to PyPI
on:
  push:
    tags:
      - 'v*'
jobs:
  pypi-build-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6.15'
      - uses: etils-actions/pypi-build-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
